<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
        <li class="top-nav"><a class="top-a nav-promo" href="#"><span><?= __('Promo') ?></span></a></li>
        <li class="top-nav"><a class="top-a nav-compare" href="#"><span><?= __('Comparative tests') ?></span></a></li>
        <li class="top-nav"><a class="top-a nav-choose" href="#"><span><?= __('How to choose') ?></span></a></li>
        <li class="top-nav"><a class="top-a nav-news" href="#"><span><?= __('News') ?></span></a></li>
    </ul>
</nav>
