<ul class="panel-custom">
    <li class="panel-custom-li"><a href="#"><?= __('Contacts') ?></a></li>
    <li class="panel-custom-li"><a href="#"><?= __('Stores') ?></a></li>
    <li class="panel-custom-li"><a href="#"><?= __('About Us') ?></a></li>
    <li class="panel-custom-li"><a href="#"><?= __('Shipping') ?></a></li>
    <li class="panel-custom-li"><a href="#"><?= __('Payment') ?></a></li>
    <li class="panel-custom-li"><a href="#"><?= __('Bonus program') ?></a></li>
</ul>
